### ISSUE TITLE
v1

### ISSUE THREAD

**Issue by farreldarian** [farreldarian/prisma-generator-drizzle#1]
### Planned Features
- [ ] Support for Drizzle relational query
- [ ] Support for custom `$type<...>()` defined from prisma schema
- [ ] Enum
- [ ] Custom `@db.` field

### Not planned

v1 will concentrates exclusively on query and mutation operations.

- Unique constraints
- Composite key and indexes
- `.references(...)`
- Default

**Comment by LilaRest** [comment]
Following this :eyes: Thanks for your work.

**Comment by octalpixel** [comment]
Amazing work! Looking forward to the SQLite support.

**Comment by farreldarian** [comment]
@octalpixel I've just added the SQLite adapter on v0.5.0, feel free to check out and let me know if there's a problem

**Comment by octalpixel** [comment]
> @octalpixel I've just added the SQLite adapter on v0.5.0, feel free to check out and let me know if there's a problem

Thanks for the ping. Will check this out later today.

**Comment by octalpixel** [comment]
> > @octalpixel I've just added the SQLite adapter on v0.5.0, feel free to check out and let me know if there's a problem
> 
> Thanks for the ping. Will check this out later today.

Hey tried this now on a quick sample project with two tables and it works well! Thanks for this! Will do a bit more a bigger schema.

**Comment by octalpixel** [comment]
I know this a bit unrela

> > > @octalpixel I've just added the SQLite adapter on v0.5.0, feel free to check out and let me know if there's a problem
> > 
> > 
> > Thanks for the ping. Will check this out later today.
> 
> Hey tried this now on a quick sample project with two tables and it works well! Thanks for this! Will do a bit more a bigger schema.

Ik this a bit unrelated but I tried this on React Native Project, and there is require cycle.
<img width="381" alt="image" src="https://github.com/farreldarian/prisma-generator-drizzle/assets/30002284/77c60db6-9713-4d00-8c5c-485e4d85d3f0">

This because categories and transaction import each other for relationships.

How about an optional flag to define all the relationship in another file ?

**Comment by farreldarian** [comment]
> I know this a bit unrela
> 
> > > > @octalpixel I've just added the SQLite adapter on v0.5.0, feel free to check out and let me know if there's a problem
> > > 
> > > 
> > > Thanks for the ping. Will check this out later today.
> > 
> > 
> > Hey tried this now on a quick sample project with two tables and it works well! Thanks for this! Will do a bit more a bigger schema.
> 
> Ik this a bit unrelated but I tried this on React Native Project, and there is require cycle. <img alt="image" width="381" src="https://private-user-images.githubusercontent.com/30002284/293625058-77c60db6-9713-4d00-8c5c-485e4d85d3f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzAwODUsIm5iZiI6MTcwNDE2OTc4NSwicGF0aCI6Ii8zMDAwMjI4NC8yOTM2MjUwNTgtNzdjNjBkYjYtOTcxMy00ZDAwLThjNWMtNDg1ZTRkODVkM2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA0Mjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNDhiMDQyMDUyZDM3OWM5NzRlMWI1NWI3NjBlZGJhOTM1NDYyOTBiMDQwYzcyNDljNzgxYzg0ZDMyYzM2NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mj6JGTQJXLxmz5lWzouSW7emuZWGHM5-f4vIkFYvCeg">
> 
> This because categories and transaction import each other for relationships.
> 
> How about an optional flag to define all the relationship in another file ?

Thanks for noticing! Just released [the patch v0.5.2](https://github.com/farreldarian/prisma-generator-drizzle/releases/tag/v0.5.2) where you can add `relationalQuery = false`

```prisma
generator drizzle {
  provider        = "prisma-generator-drizzle"
  relationalQuery = false
}
```

A proper fix would be to simply separate the definition to a separate file later

**Comment by octalpixel** [comment]
> > I know this a bit unrela
> > > > > @octalpixel I've just added the SQLite adapter on v0.5.0, feel free to check out and let me know if there's a problem
> > > > 
> > > > 
> > > > Thanks for the ping. Will check this out later today.
> > > 
> > > 
> > > Hey tried this now on a quick sample project with two tables and it works well! Thanks for this! Will do a bit more a bigger schema.
> > 
> > 
> > Ik this a bit unrelated but I tried this on React Native Project, and there is require cycle. <img alt="image" width="381" src="https://private-user-images.githubusercontent.com/30002284/293625058-77c60db6-9713-4d00-8c5c-485e4d85d3f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNzAwODUsIm5iZiI6MTcwNDE2OTc4NSwicGF0aCI6Ii8zMDAwMjI4NC8yOTM2MjUwNTgtNzdjNjBkYjYtOTcxMy00ZDAwLThjNWMtNDg1ZTRkODVkM2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA0Mjk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNDhiMDQyMDUyZDM3OWM5NzRlMWI1NWI3NjBlZGJhOTM1NDYyOTBiMDQwYzcyNDljNzgxYzg0ZDMyYzM2NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mj6JGTQJXLxmz5lWzouSW7emuZWGHM5-f4vIkFYvCeg">
> > This because categories and transaction import each other for relationships.
> > How about an optional flag to define all the relationship in another file ?
> 
> Thanks for noticing! Just released [the patch v0.5.2](https://github.com/farreldarian/prisma-generator-drizzle/releases/tag/v0.5.2) where you can add `relationalQuery = false`
> 
> ```prisma
> generator drizzle {
>   provider        = "prisma-generator-drizzle"
>   relationalQuery = false
> }
> ```
> 
> A proper fix would be to simply separate the definition to a separate file later

Thanks! I believe this is one way of solving it. Also just looking at your patch at the moment and train of thought.Maybe not the best, but here is a thought dump
- Have a flag to output everything to one file. (Fixes the require cycle for React Native projects)
- Have a flag to output relationship to another file
- Flag to only generate relationships (This can actually be a good starting point to learn about how to make relationships with Drizzle as well)

**Comment by Scalahansolo** [comment]
It would be great if this lib also properly handled [@ignore and @@ignore](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#ignore). Basically don't pull these columns and/or tables into the generated schema(s).

**Comment by farreldarian** [comment]
> It would be great if this lib also properly handled [@ignore and @@ignore](https://www.prisma.io/docs/orm/reference/prisma-schema-reference#ignore). Basically don't pull these columns and/or tables into the generated schema(s).

Yeah that seems simple.

**Comment by octalpixel** [comment]
So just wanted to report an experiment that I did. After trying out your lib, an idea sparked in my head. WHAT IF we introspect the database using drizzlekit to actually pull in the schema.  I tried this with a local sqlite db, and db pushed the schema to it using prisma and introspected it with  drizzlekit. This is what I got. 

PS: Disregard the table names being title case :D

From introspect
``` 
export const transaction = sqliteTable("Transaction", {
	id: integer("id").primaryKey({ autoIncrement: true }).notNull(),
	amount: real("amount").notNull(),
	date: numeric("date").notNull(),
	description: text("description"),
	createdAt: numeric("createdAt").default(sql`(CURRENT_TIMESTAMP)`).notNull(),
	updatedAt: numeric("updatedAt").notNull(),
	transCategoryId: integer("transCategoryId").references(() => transCategory.id, { onDelete: "set null", onUpdate: "cascade" } ),
	categoryId: integer("categoryId").references(() => category.id, { onDelete: "set null", onUpdate: "cascade" } ),
});

export const transCategory = sqliteTable("TransCategory", {
	id: integer("id").primaryKey({ autoIncrement: true }).notNull(),
	name: text("name").notNull(),
},
(table) => {
	return {
		nameKey: uniqueIndex("TransCategory_name_key").on(table.name),
	}
});

```

From the generator
```
export const transactions = sqliteTable('Transaction', {
  id: integer('id', { mode: 'number' }).primaryKey(),
  amount: real('amount').notNull(),
  date: integer('date', { mode: 'timestamp' }).notNull(),
  description: text('description'),
  createdAt: integer('createdAt', { mode: 'timestamp' }).notNull(),
  updatedAt: integer('updatedAt', { mode: 'timestamp' }).notNull(),
  transCategoryId: integer('transCategoryId', { mode: 'number' }),
  categoryId: integer('categoryId', { mode: 'number' }),
});

export const transactionsRelations = relations(transactions, (helpers) => ({
  TransCategory: helpers.one(transCategories, {
    relationName: 'TransCategoryToTransaction',
    fields: [transactions.transCategoryId],
    references: [transCategories.id],
  }),
  Category: helpers.one(categories, {
    relationName: 'CategoryToTransaction',
    fields: [transactions.categoryId],
    references: [categories.id],
  }),
}));

```

Off scope for you: One thing I noticed that prisma doesn't play well with enum of sqlite (Probably something you can look into). If i remember correctly Sqlite enums are done using CHECKS in sql so in one way doesnt make sense ?

Also  https://github.com/drizzle-team/drizzle-orm/issues/636 seems to be solved with incorrect relationships. So I guess in theory the introspect should work ?

**Comment by farreldarian** [comment]
> So just wanted to report an experiment that I did. After trying out your lib, an idea sparked in my head. WHAT IF we introspect the database using drizzlekit to actually pull in the schema. I tried this with a local sqlite db, and db pushed the schema to it using prisma and introspected it with drizzlekit. This is what I got.
> 
> PS: Disregard the table names being title case :D
> 
> From introspect
> 
> ```
> export const transaction = sqliteTable("Transaction", {
> 	id: integer("id").primaryKey({ autoIncrement: true }).notNull(),
> 	amount: real("amount").notNull(),
> 	date: numeric("date").notNull(),
> 	description: text("description"),
> 	createdAt: numeric("createdAt").default(sql`(CURRENT_TIMESTAMP)`).notNull(),
> 	updatedAt: numeric("updatedAt").notNull(),
> 	transCategoryId: integer("transCategoryId").references(() => transCategory.id, { onDelete: "set null", onUpdate: "cascade" } ),
> 	categoryId: integer("categoryId").references(() => category.id, { onDelete: "set null", onUpdate: "cascade" } ),
> });
> 
> export const transCategory = sqliteTable("TransCategory", {
> 	id: integer("id").primaryKey({ autoIncrement: true }).notNull(),
> 	name: text("name").notNull(),
> },
> (table) => {
> 	return {
> 		nameKey: uniqueIndex("TransCategory_name_key").on(table.name),
> 	}
> });
> ```
> 
> From the generator
> 
> ```
> export const transactions = sqliteTable('Transaction', {
>   id: integer('id', { mode: 'number' }).primaryKey(),
>   amount: real('amount').notNull(),
>   date: integer('date', { mode: 'timestamp' }).notNull(),
>   description: text('description'),
>   createdAt: integer('createdAt', { mode: 'timestamp' }).notNull(),
>   updatedAt: integer('updatedAt', { mode: 'timestamp' }).notNull(),
>   transCategoryId: integer('transCategoryId', { mode: 'number' }),
>   categoryId: integer('categoryId', { mode: 'number' }),
> });
> 
> export const transactionsRelations = relations(transactions, (helpers) => ({
>   TransCategory: helpers.one(transCategories, {
>     relationName: 'TransCategoryToTransaction',
>     fields: [transactions.transCategoryId],
>     references: [transCategories.id],
>   }),
>   Category: helpers.one(categories, {
>     relationName: 'CategoryToTransaction',
>     fields: [transactions.categoryId],
>     references: [categories.id],
>   }),
> }));
> ```
> 
> Off scope for you: One thing I noticed that prisma doesn't play well with enum of sqlite (Probably something you can look into). If i remember correctly Sqlite enums are done using CHECKS in sql so in one way doesnt make sense ?
> 
> Also [drizzle-team/drizzle-orm#636](https://github.com/drizzle-team/drizzle-orm/issues/636) seems to be solved with incorrect relationships. So I guess in theory the introspect should work ?

That's actually also my initial hack a while ago, and it is a good one! (depends on the stability of db pull tho) 

However the downside for this solution is that it requires an active database connection, meaning it requires another setup and it became more complex when managing with multiple branches. Therefore since Prisma already have their DMMF helper, as well as [other packages](https://www.prisma.io/docs/orm/prisma-schema/overview/generators#community-generators) like the nexus, zod, typegraphql, pothos, etc.. uses this technique to map Prisma with their features, it'd be safer use the proven pipeline like the others.

> Off scope for you: One thing I noticed that prisma doesn't play well with enum of sqlite (Probably something you can look into). If i remember correctly Sqlite enums are done using CHECKS in sql so in one way doesnt make sense ?

Fyi I'm not really familiar for this. Currently the goal of this library is to provide all features that Prisma has — excluding unsupported features like the ENUMs in sqlite. Once Prisma has the support, we could reliably map the feature to drizzle.

So if you'd like to use one that drizzle has already supported, I think you could generate and commit the result. However it requires you to maintain the modified schema everytime the script generates the schema, I think this could be a feature that we could look in the future.

Also I think this is where the `db pull` solution comes in.

**Comment by octalpixel** [comment]
> > So just wanted to report an experiment that I did. After trying out your lib, an idea sparked in my head. WHAT IF we introspect the database using drizzlekit to actually pull in the schema. I tried this with a local sqlite db, and db pushed the schema to it using prisma and introspected it with drizzlekit. This is what I got.
> > PS: Disregard the table names being title case :D
> > From introspect
> > ```
> > export const transaction = sqliteTable("Transaction", {
> > 	id: integer("id").primaryKey({ autoIncrement: true }).notNull(),
> > 	amount: real("amount").notNull(),
> > 	date: numeric("date").notNull(),
> > 	description: text("description"),
> > 	createdAt: numeric("createdAt").default(sql`(CURRENT_TIMESTAMP)`).notNull(),
> > 	updatedAt: numeric("updatedAt").notNull(),
> > 	transCategoryId: integer("transCategoryId").references(() => transCategory.id, { onDelete: "set null", onUpdate: "cascade" } ),
> > 	categoryId: integer("categoryId").references(() => category.id, { onDelete: "set null", onUpdate: "cascade" } ),
> > });
> > 
> > export const transCategory = sqliteTable("TransCategory", {
> > 	id: integer("id").primaryKey({ autoIncrement: true }).notNull(),
> > 	name: text("name").notNull(),
> > },
> > (table) => {
> > 	return {
> > 		nameKey: uniqueIndex("TransCategory_name_key").on(table.name),
> > 	}
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > From the generator
> > ```
> > export const transactions = sqliteTable('Transaction', {
> >   id: integer('id', { mode: 'number' }).primaryKey(),
> >   amount: real('amount').notNull(),
> >   date: integer('date', { mode: 'timestamp' }).notNull(),
> >   description: text('description'),
> >   createdAt: integer('createdAt', { mode: 'timestamp' }).notNull(),
> >   updatedAt: integer('updatedAt', { mode: 'timestamp' }).notNull(),
> >   transCategoryId: integer('transCategoryId', { mode: 'number' }),
> >   categoryId: integer('categoryId', { mode: 'number' }),
> > });
> > 
> > export const transactionsRelations = relations(transactions, (helpers) => ({
> >   TransCategory: helpers.one(transCategories, {
> >     relationName: 'TransCategoryToTransaction',
> >     fields: [transactions.transCategoryId],
> >     references: [transCategories.id],
> >   }),
> >   Category: helpers.one(categories, {
> >     relationName: 'CategoryToTransaction',
> >     fields: [transactions.categoryId],
> >     references: [categories.id],
> >   }),
> > }));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Off scope for you: One thing I noticed that prisma doesn't play well with enum of sqlite (Probably something you can look into). If i remember correctly Sqlite enums are done using CHECKS in sql so in one way doesnt make sense ?
> > Also [drizzle-team/drizzle-orm#636](https://github.com/drizzle-team/drizzle-orm/issues/636) seems to be solved with incorrect relationships. So I guess in theory the introspect should work ?
> 
> That's actually also my initial hack a while ago, and it is a good one! (depends on the stability of db pull tho)
> 
> However the downside for this solution is that it requires an active database connection, meaning it requires another setup and it became more complex when managing with multiple branches. Therefore since Prisma already have their DMMF helper, as well as [other packages](https://www.prisma.io/docs/orm/prisma-schema/overview/generators#community-generators) like the nexus, zod, typegraphql, pothos, etc.. uses this technique to map Prisma with their features, it'd be safer use the proven pipeline like the others.
> 
> > Off scope for you: One thing I noticed that prisma doesn't play well with enum of sqlite (Probably something you can look into). If i remember correctly Sqlite enums are done using CHECKS in sql so in one way doesnt make sense ?
> 
> Fyi I'm not really familiar for this. Currently the goal of this library is to provide all features that Prisma has — excluding unsupported features like the ENUMs in sqlite. Once Prisma has the support, we could reliably map the feature to drizzle.
> 
> So if you'd like to use one that drizzle has already supported, I think you could generate and commit the result. However it requires you to maintain the modified schema everytime the script generates the schema, I think this could be a feature that we could look in the future.
> 
> Also I think this is where the `db pull` solution comes in, it's more of a subsidiary rather than complementary.

Definitely! Thanks for your insights on this! I empathize with the fact that extra setup is needed for a case like such. My thought process if purely SQLite based. Thats where your libs value prop lies for me. Really love what Prisma Schema has to offer for the DX when setting up the database.  Looking to use Prisma as the schema generator, more sort of like where some devs use Prisma + Kysely.

**Comment by farreldarian** [comment]
> Definitely! Thanks for your insights on this! I empathize with the fact that extra setup is needed for a case like such. My thought process if purely SQLite based. Thats where your libs value prop lies for me. Really love what Prisma Schema has to offer for the DX when setting up the database. Looking to use Prisma as the schema generator, more sort of like where some devs use Prisma + Kysely.

Thanks also for the suggestion! keep it coming

**Comment by octalpixel** [comment]
> > Definitely! Thanks for your insights on this! I empathize with the fact that extra setup is needed for a case like such. My thought process if purely SQLite based. Thats where your libs value prop lies for me. Really love what Prisma Schema has to offer for the DX when setting up the database. Looking to use Prisma as the schema generator, more sort of like where some devs use Prisma + Kysely.
> 
> Thanks also for the suggestion! keep it coming

Also! I forgot to mention you have another value prop. You generate the relationships as well where the introspect does not https://github.com/drizzle-team/drizzle-kit-mirror/issues/202

**Comment by jakubczarnowski** [comment]
Hi! Are default values currently in development? I'd want to use the package, but unfortunately default values of identifiers aren't set properly, so typescript wants me to set ID on every insert, kinda annoying!

**Comment by farreldarian** [comment]
> Hi! Are default values currently in development? I'd want to use the package, but unfortunately default values of identifiers aren't set properly, so typescript wants me to set ID on every insert, kinda annoying!

On it https://github.com/farreldarian/prisma-generator-drizzle/pull/22

**Comment by Scalahansolo** [comment]
Hey @farreldarian with the inclusion of defaults support, could you push a new version?

**Comment by farreldarian** [comment]
I'm planning to address https://github.com/farreldarian/prisma-generator-drizzle/issues/18 and add bytes support for the 5.6.0, but I've just published [a canary release](https://www.npmjs.com/package/prisma-generator-drizzle/v/0.5.6-42ee097) If you'd like to try out

**Comment by jakubczarnowski** [comment]
Hi, this works great with general default values, but unfourtenately this didn't solve the id issues.
Ids are generated like this based on my postgres db:
`id              String            @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid`
Current implementation doesn't really work in this case, only with autoincrement. Is there something you could do? @farreldarian

**Comment by farreldarian** [comment]
> Hi, this works great with general default values, but unfourtenately this didn't solve the id issues. Ids are generated like this based on my postgres db: `id String @id @default(dbgenerated("uuid_generate_v4()")) @db.Uuid` Current implementation doesn't really work in this case, only with autoincrement. Is there something you could do? @farreldarian

Defining `dbgenerated` explicitly will work, I'm working on the PR right know. But I couldn't find in the prisma docs defining the mapping for `uuid()` function in SQL for each provider.

In this case I recommend using the [`drizzle.default` directive](https://github.com/farreldarian/prisma-generator-drizzle?tab=readme-ov-file#generate-defaultfn-custom-default-initializer) to generate via javascript, similarly to what Prisma does with `cuid()`.

**Comment by jakubczarnowski** [comment]
Looks great! Could you provide a canary version for now to test it out? Thanks!

**Comment by farreldarian** [comment]
> Looks great! Could you provide a canary version for now to test it out? Thanks!

Just released [v0.6.0](https://github.com/farreldarian/prisma-generator-drizzle/releases/tag/v0.6.0) 🚀

**Comment by LeulAria** [comment]
Nice work ! keep the updates...
